/* Generated By:JavaCC: Do not edit this line. KarloffParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APAR = 8;
  /** RegularExpression Id. */
  int FPAR = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int FUNC = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int ATRIB = 17;
  /** RegularExpression Id. */
  int MINOR = 18;
  /** RegularExpression Id. */
  int MINOR_EQ = 19;
  /** RegularExpression Id. */
  int MAJOR = 20;
  /** RegularExpression Id. */
  int MAJOR_EQ = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int MUL = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int COMM = 26;
  /** RegularExpression Id. */
  int DOTCOMM = 27;
  /** RegularExpression Id. */
  int SYSOUT = 28;
  /** RegularExpression Id. */
  int SYSREAD = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int REPEAT = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int VAR = 34;
  /** RegularExpression Id. */
  int TRUE = 35;
  /** RegularExpression Id. */
  int FALSE = 36;
  /** RegularExpression Id. */
  int NUM = 37;
  /** RegularExpression Id. */
  int ID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"bool\"",
    "\"integer\"",
    "\"void\"",
    "\"func\"",
    "\"+\"",
    "\"-\"",
    "\"==\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&\"",
    "\"|\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\";\"",
    "\"System.output\"",
    "\"System.readint\"",
    "\"return\"",
    "\"repeat\"",
    "\"while\"",
    "\"if\"",
    "\"newVar\"",
    "\"true\"",
    "\"false\"",
    "<NUM>",
    "<ID>",
  };

}
