/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APAR = 8;
  /** RegularExpression Id. */
  int FPAR = 9;
  /** RegularExpression Id. */
  int ATRIB = 10;
  /** RegularExpression Id. */
  int DOTCOMM = 11;
  /** RegularExpression Id. */
  int COMM = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int MUL = 16;
  /** RegularExpression Id. */
  int BOOL = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int SYSOUT = 19;
  /** RegularExpression Id. */
  int SYSREAD = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int REPEAT = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int VAR = 25;
  /** RegularExpression Id. */
  int EQUALS = 26;
  /** RegularExpression Id. */
  int MINOR = 27;
  /** RegularExpression Id. */
  int MAJOR = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int ID = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"/\"",
    "\"-\"",
    "\"*\"",
    "\"bool\"",
    "\"integer\"",
    "\"System.out\"",
    "\"System.readint\"",
    "\"return\"",
    "\"repeat\"",
    "\"while\"",
    "\"if\"",
    "\"newVar\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"|\"",
    "<NUM>",
    "<ID>",
  };

}
