/* Karloff.java */
/* Generated By:JavaCC: Do not edit this line. Karloff.java */
import java.io.*;
public class Karloff implements KarloffConstants {

    public static void main(String args[]) throws ParseException, IOException {

        Karloff analisador = new Karloff(new FileInputStream(args[0]));
        analisador.Karloff();
    }

  static final public void Karloff() throws ParseException {Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIN:
      case ACHAVES:
      case FCHAVES:
      case APAR:
      case FPAR:
      case ATRIB:
      case DOTCOMM:
      case COMM:
      case PLUS:
      case DIV:
      case MINUS:
      case MUL:
      case BOOL:
      case INT:
      case SYSOUT:
      case SYSREAD:
      case RETURN:
      case REPEAT:
      case WHILE:
      case IF:
      case VAR:
      case EQUALS:
      case MINOR:
      case MAJOR:
      case AND:
      case OR:
      case NUM:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIN:{
        jj_consume_token(MAIN);
System.out.println("Palavra reservada: main");
        break;
        }
      case ACHAVES:{
        jj_consume_token(ACHAVES);
System.out.println("Abre chaves: {");
        break;
        }
      case FCHAVES:{
        jj_consume_token(FCHAVES);
System.out.println("Fecha chaves: }");
        break;
        }
      case APAR:{
        jj_consume_token(APAR);
System.out.println("Abre parenteses: (");
        break;
        }
      case FPAR:{
        jj_consume_token(FPAR);
System.out.println("Fecha parenteses: )");
        break;
        }
      case ATRIB:{
        jj_consume_token(ATRIB);
System.out.println("Atribui\u00e7\u00e3o: =");
        break;
        }
      case DOTCOMM:{
        jj_consume_token(DOTCOMM);
System.out.println("Ponto e V\u00edrgula: ;");
        break;
        }
      case COMM:{
        jj_consume_token(COMM);
System.out.println("V\u00edrgula: ,");
        break;
        }
      case PLUS:{
        jj_consume_token(PLUS);
System.out.println("Soma: +");
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
System.out.println("Divis\u00e3o: /");
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
System.out.println("Menos: -");
        break;
        }
      case MUL:{
        jj_consume_token(MUL);
System.out.println("Multiplica\u00e7\u00e3o: *");
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
System.out.println("Tipo booleano: bool");
        break;
        }
      case INT:{
        jj_consume_token(INT);
System.out.println("Tipo inteiro: integer");
        break;
        }
      case SYSOUT:{
        t = jj_consume_token(SYSOUT);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case VAR:{
        t = jj_consume_token(VAR);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case SYSREAD:{
        t = jj_consume_token(SYSREAD);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case RETURN:{
        t = jj_consume_token(RETURN);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case IF:{
        t = jj_consume_token(IF);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case WHILE:{
        t = jj_consume_token(WHILE);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case REPEAT:{
        t = jj_consume_token(REPEAT);
System.out.println("Palavra reservada: " + t.image);
        break;
        }
      case NUM:{
        t = jj_consume_token(NUM);
System.out.println("N\u00famero: " + t.image);
        break;
        }
      case ID:{
        t = jj_consume_token(ID);
System.out.println("Identificador: " + t.image);
        break;
        }
      case EQUALS:{
        jj_consume_token(EQUALS);
System.out.println("Operador de igualdade: ==");
        break;
        }
      case MINOR:{
        jj_consume_token(MINOR);
System.out.println("Operador menor: <");
        break;
        }
      case MAJOR:{
        jj_consume_token(MAJOR);
System.out.println("Operador maior: >");
        break;
        }
      case AND:{
        jj_consume_token(AND);
System.out.println("Operador l\u00f3gico AND: &");
        break;
        }
      case OR:{
        jj_consume_token(OR);
System.out.println("Operador l\u00f3gico OR: |");
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public KarloffTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xffffffe0,0xffffffe0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1,0x1,};
	}

  /** Constructor with InputStream. */
  public Karloff(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Karloff(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new KarloffTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Karloff(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new KarloffTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new KarloffTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Karloff(KarloffTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(KarloffTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[33];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 2; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 33; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
